version: '2'

services:
  web:
    restart: always
    container_name: PortManager
    build: .
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=LOCAL
      - SECRET_KEY='&i4hv(y#kh6yl=s5jls&-@)5h!8t!8p^rkr0=p9f7oswvlw8#@'
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=port_manager
      - DATABASE_USER=root
      - DATABASE_PASSWORD=
    command: ./wait-for-it.sh db:3306 -- ./run_web.sh
    ports:
      - '8000:8000'
    links:
      - db
    depends_on:
      - db
  db:
    restart: always
    container_name: PortManagerMYSQL
    image: mysql:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=TRUE
      - MYSQL_DATABASE=port_manager
    command: [mysqld, --character-set-server=utf8, --collation-server=utf8_general_ci]