# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170227_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='home_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.Address'),
        ),
    ]
