# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20170227_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='home_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='web.Address'),
        ),
    ]
