# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20170227_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='home_address',
        ),
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('Home Address', 'Home Address'), ('Postal Address', 'Postal Address'), ('Other', 'Other')], default='Home Address', max_length=50),
        ),
        migrations.AddField(
            model_name='address',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Person'),
        ),
    ]
