# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20170227_1148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContentHazard',
            new_name='CargoHazard',
        ),
        migrations.AlterField(
            model_name='dockmanifest',
            name='departure',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set([('person', 'address_type')]),
        ),
    ]
