# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20170227_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargohazard',
            name='web_icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cargohazard',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
