# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20170301_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dock',
            name='docked_ship',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dock', to='web.Ship'),
        ),
    ]
