# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20170301_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
