# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 09:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0012_auto_20170301_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.UserProfile'),
        ),
        migrations.AlterField(
            model_name='dockemployee',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.UserProfile'),
        ),
        migrations.AlterField(
            model_name='shipcaptain',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.UserProfile'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
