# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20170301_0941'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Person',
        ),
    ]
